services:
  database:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bunnybuddy
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
  server:
    build:
      context: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    command: uvicorn main:app --reload --host 0.0.0.0
